name: TeleportPlugin
main: com.example.teleportplugin.TeleportPlugin
version: 1.0
api-version: 1.21
description: Spigot plugin for /home, /sethome, /tp, /trade commands with death location tracking and product scraping
authors: ["p-astro16"]

commands:
  home:
    description: Teleport to your home
  sethome:
    description: Set your home location
  tp:
    description: Request to teleport to another player
  tpaccept:
    description: Accept a teleport request
  trade:
    description: Trade items with another player
  product:
    description: Manage product information with fallback scraping methods
    usage: /product <info|list|search|recover|stats|rarity> [args]

permissions:
  product.admin:
    description: Allows running product recovery operations
    default: op
